### ISSUE TITLE
Color of the Top Bar

### ISSUE THREAD

**Issue by freecicero** [nicolasprigent/Dokuwiki-Kiwiki-Theme#1]
My first item to customize would be the "top bar" (if there really is one).  Does one of the custom colors control that selection alone?  thanks!

**Comment by nicolasprigent** [comment]
hi @freecicero  that seems to be something that I could implement. I'll make it in the next days and let you know. Does this template suits your needs ?

**Comment by nicolasprigent** [comment]
Hey, I had some time tonight and it was really not much to implement, you've got a new version with a new parameter, both for light and dark versions. Enjoy !

**Comment by nicolasprigent** [comment]
I'm closing the issue
