### ISSUE TITLE
I love how the left menu is sticky! - but make the left menu scrollable when overflowing (the end becomes hidden)

### ISSUE THREAD

**Issue by Chris75forumname** [nicolasprigent/Dokuwiki-Kiwiki-Theme#10]
I love how the left menu is sticky! But make the left menu scrollable when overflowing. The end becomes hidden, when the toc becomes too long.

**Comment by nicolasprigent** [comment]
hello @Chris75forumname I've made an update, now you can choose a max size in pixels for the toc. Let me know if that suits your needs.

**Comment by nicolasprigent** [comment]
If you need some more update, let me know on a new issue, I close this one for now.

**Comment by Chris75forumname** [comment]
Thanks! Great! 😃
