### ISSUE TITLE
[feature request] add a down button (and some other features)

### ISSUE THREAD

**Issue by Chris75forumname** [nicolasprigent/Dokuwiki-Kiwiki-Theme#12]
Hi, I just love your template and I will use it personally. I would nominate your template for the DokuWiki best template design award! 
One of the first things I modified when I started with DokuWiki, I cloned the top button and morphed it into a down button in the template. I integrated it into the page menu, in symmetry with the top button. This would be a nice feat to have here too. 😃

**Comment by nicolasprigent** [comment]
Hey thanks a lot for the kind words. I myself use this theme for my personal use, I think we got the same tastes regarding webdesign ☺️ 
I'm not totally sure of what you're referring to, could you provide a screenshot of what you described?

**Comment by Chris75forumname** [comment]
I refer to on of the [main features](https://www.dokuwiki.org/template:kiwiki#main_features) 
"Back to top button fixed on the bottom right corner of the screen"

What I am trying to say, is: It would be nice to have a "down button", similar to the "Back-to-top-button", fixed on the upper right corner of the screen.

Cheers!

**Comment by Chris75forumname** [comment]
Yes, that would be great!! Cheers!

**Comment by Chris75forumname** [comment]
BTW: I have two more useful features, I propose to implement.

- I added the ACL for the current page in the footer, like so: 
  "This page is visible to groups: @staff, @management. This page is invisible to groups: @ALL, @user, @intern."
- I added a "fullscreen" button in the top bar (next to the dark mode button). It effectively hides the sidebar and stretches `#dokuwiki__content` to 100% width. (using jQuery toggleClass)

But, these are only suggestions! Yours, Chris

**Comment by nicolasprigent** [comment]
Do you have the code that you've implemented for acl ? the fullscreen is a nice suggestion too

**Comment by Chris75forumname** [comment]
I used this code from the tips and tricks section: https://www.dokuwiki.org/tips:display_acls.
I described this in further detail from here on: https://forum.dokuwiki.org/d/21636-acl-deny-a-user-group-to-a-namespace/8

**Comment by nicolasprigent** [comment]
You can re-install the theme to see the new features that you can add or remove from the admin panel of the theme :
- go to bottom
- full screen mode
- view connected user in footer
- view acl infos in footer

For the last one that you've asked, you only want a list of the groups that the user belong too, that's right ?
I'll see what I can do but it should not be a big deal.

**Comment by Chris75forumname** [comment]
Whow! That was a quick reaction! How did you do that?? 😄 
- the go bottom button is great!
- the fullscreen mode is magnificent!
- ACL in the footer: No, I didn't mean the logged in user. This info is already shown on the user button in the top row.


> For the last one that you've asked, you only want a list of the groups that the user belong too, that's right ?

Yes, exactly!

**Comment by nicolasprigent** [comment]
Regarding the logged in user info in the footer, it's a default feature that I've deleted before, I made it as an option for convenience and/or compatibility with other plugins. Regarding the acl information, I've implemented the code that you've linked in the first link. I haven't see that you've made a custom one yourself on the second link. Is that what you need ?
Thanks for the nice words about the other stuff :)

**Comment by Chris75forumname** [comment]
> I haven't see that you've made a custom one yourself on the second link. Is that what you need ?

Yes exactly! It was not much customized by me, but I didn't see it come through in the template. It's supposed to say:
`page visible to: <list of groups>`

Cheers!

**Comment by nicolasprigent** [comment]
isn't it an information that causes some security issues ? Would this be visible only to admins ?

**Comment by nicolasprigent** [comment]
Oh you've said it above "someone who is editing can see, who will be able to view the (sensitive) data that he is about to add", so I will make it visible only to people that have read access on the page

**Comment by Chris75forumname** [comment]
> I will make it visible only to people that have edit access on the page

Yes, great! And you can also extract the passage that says: `page hidden to: ... `

**Comment by nicolasprigent** [comment]
I'm on it, I haven't made the proper code yet :D

**Comment by Chris75forumname** [comment]
In fact, I canged the output to from within the function, like so:

	if (count($list)) {
	    sort($list);
		echo '<div class="page_acls" style="margin-top:5px;"><bdi>Leserechte</bdi><span> · Seite sichtbar für: ';
		echo join(', ',$list);
		echo '</span>';
	}

and removed the line `return $return;`

**Comment by nicolasprigent** [comment]
You can re-install the theme to see the update. Only people that can edit the current page can view the information. And I've made some styling also.

**Comment by Chris75forumname** [comment]
AMAZING! You are a just unbelievable! 
THANK YOU VERY MUCH!!! 
You made my day!
This is open source at it's finest! 😄

**Comment by Chris75forumname** [comment]
Very cool! Many thanks! I am so happy, to see all my favorite features in this beautiful template! 
It's been a pleasure! 😃

**Comment by nicolasprigent** [comment]
Thanks, have a great day
