### ISSUE TITLE
Menu button hides TOC, not sidebar/navigation on mobile

### ISSUE THREAD

**Issue by ToeiRei** [nicolasprigent/Dokuwiki-Kiwiki-Theme#13]
The menu (h3) has that + next to it - and it looks like it would hide the navigation - but instead it just hides the TOC and thus the navigation takes up most of the screen.

**Comment by ToeiRei** [comment]
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/5990591/82b47407-f649-433b-a4d2-067f41e30de6)

**Comment by nicolasprigent** [comment]
You can update the template, it should work now. Let me know !

**Comment by ToeiRei** [comment]
Thank you - I'll test

**Comment by ToeiRei** [comment]
Fix worked. Thanks
