### ISSUE TITLE
Missing Edit-Button when authenticated with authldap

### ISSUE THREAD

**Issue by christianprim** [nicolasprigent/Dokuwiki-Kiwiki-Theme#14]
If a user is authenticated with authplain (standard), he can edit pages by clicking on the little pen-button on the top of the page content.

See:
![Screenshot 2023-11-22 19 36 28](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/5284928/db7d28f6-f083-437f-8f26-2c9d5b5bcb61)

If the user is authenticated with the ldap-server (authldap), the buttons are missing. He can use the menu-entry to edit a page, but it's not as easy.

See:
![Screenshot 2023-11-22 19 38 27](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/5284928/d06cf988-3731-4627-a50e-0137d3db4c1b)

**Comment by nicolasprigent** [comment]
hello @christianprim , I'm not really familiar with ldap authentification, and I don't know how to test it. Are you sure that Access control is correctly configured ?

**Comment by nicolasprigent** [comment]
In my code, only admins have access to this icon, I'll maybe check for permissions instead, I think it's why it doesn't show up

**Comment by nicolasprigent** [comment]
Ok, I think I'll make an update, I'm checking permissions instead of only checking if it's an admin. Please reinstall the theme and let me know if that works.

**Comment by christianprim** [comment]
It works! Many thanks.

**Comment by nicolasprigent** [comment]
Great thanks for the test ;)
