### ISSUE TITLE
Toolbar button readable ?

### ISSUE THREAD

**Issue by baudryj** [nicolasprigent/Dokuwiki-Kiwiki-Theme#15]
Hi,

I did'nt find a way to get button (toolbar) readable without impact on other buttons ...
any idea ? a white background would be good.

![Capture d’écran du 2023-11-24 11-02-56](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/259649/338b5a9f-f327-4953-aa4b-d34c2f97b410)

**Comment by baudryj** [comment]
It's default parameter ... I didn't change anything

**Comment by nicolasprigent** [comment]
Hi @baudryj I'll make some css adjustments asap, no problem.

**Comment by nicolasprigent** [comment]
hello @baudryj I've made an update on css of the toolbar buttons, tell me if it's ok for you.

**Comment by baudryj** [comment]
Thanks Nicolas !!
C'est un super thème ;-) simple et efficace ... j'adore

**Comment by nicolasprigent** [comment]
Merci pour le retour ! C'était un peu l'idée oui, je l'utilise pour mon propre wiki, je me suis dis que ça pourrait plaire à quelqu'un d'autre.
