### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Lagens78** [nicolasprigent/Dokuwiki-Kiwiki-Theme#17]
Hello :)

I'm using a code to display a table
<img width="296" alt="CODE" src="https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/156082729/1b9f1538-ebf6-486f-ae97-4edbceeac4be">

In the "normal" docuwiki, it's displayed perfectly.
<img width="299" alt="OK" src="https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/156082729/44822034-e745-4930-8b1a-059641e415e8">

In your template, this is not really the case.
<img width="304" alt="KO" src="https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/156082729/92993117-0e58-4550-981e-591f66cab588">

I no longer have a gray background, a row/column border, the alignment is no longer on the left ;(

Could you explain why please? :)

Thank you

**Comment by nicolasprigent** [comment]
hello @Lagens78 I've made some tweaks on table css code to design some parts of the dokuwiki ui, so I guess it getting above the style of your code. Do you use a specific plugin for this ? Could you please send me a table code example so that I can find what's going wrong ?

**Comment by Lagens78** [comment]
Hello, 
Thank you for your quick response.

There is nothing special in my table, it's just a test. So currently the code is really basic ;)
^ NOM ^ RÔLE ^ DT SAF ^ COURRIEL ^ N° FIXE ^ N° PORTABLE ^
| SERVICE | Monservice | - | mail1 | - | +33 (0)6 00 00 00 00 |
| TOTO | IH | dt | mail1 | - |  |
| TTI | Analyste | dt1 | mail2 | - | +33 (0)6 00 00 00 00  |
| TATA | Analyste | dt2 | mail3| - | +33 (0)6 00 00 00 00  |
| TUTU | Analyste | dt3 | mail4 | - | +33 (0)6 00 00 00 00 |
| TETE | Analyste | dt4 | mail5 | - | +33 (0)6 00 00 00 00 |

For now, I have not yet touched the configuration files of your template

About plugin, I just added the "Wrap Plugin", https://www.dokuwiki.org/plugin:wrap , But I don't use it for this test ;)

**Comment by nicolasprigent** [comment]
You can update the theme, I've added some css styling for tables :
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/66468412/0e1b6f68-0455-4b97-837e-1712c647d4e4)

**Comment by Lagens78** [comment]
Hello, 
That's perfect, many thanks. :) :) :)

**Comment by Lagens78** [comment]
I discovered another item that could be updated I think :)
Would you prefer that I close this ticket and open a new one, or may I place it here? :)

**Comment by nicolasprigent** [comment]
you can place it here, no problem

**Comment by nicolasprigent** [comment]
ok I see. I'll check this !

**Comment by nicolasprigent** [comment]
You can re-install the plugin to get the red color on the non existing page links ;)

**Comment by Lagens78** [comment]
It works, awesome :)
Thank you again and thank you for your template and availability.

**Comment by nicolasprigent** [comment]
My pleasure, don't hesitate if you find other things that bothers you
