### ISSUE TITLE
Top Header not there anymore

### ISSUE THREAD

**Issue by holisticagile** [nicolasprigent/Dokuwiki-Kiwiki-Theme#2]
Hey,

I just installed KiWiki Template and I'm a big fan. Simple and Easy.
Yet, I did run into a problem.
When I activate the template, there is no header or control buttons anymore. Only Safari the cached Version work.
I tried it with chrome, edge and firefox. It just shows the "start" page and nothing else.

Is this a config error? I could not find any help or tips. 

I put some text into "mainmenu" and into start to check. Its a fresh install. Sidebar is named "Menu".

* this is a not functioning view 
![Bildschirmfoto 2023-07-03 um 21 07 35](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/77532551/6142ded4-bb62-4034-9764-253578ca46b4)

* this is until i kill the cache on safari
![Bildschirmfoto 2023-07-03 um 21 07 27](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/77532551/0d5575ab-be65-4800-8e13-63524b001cb4)

**Comment by nicolasprigent** [comment]
Hello @holisticagile , glad you like the template ;)
Regarding your issue, it really feels like a css cache issue on the web browser side, not sure anyway.
- Have you tried to flush browser cache (ctrl+shift+r on windows or cmd+shift+del on mac I guess)
- Does it happen only on a fresh install or have you tested it on an other install ?
- to flush the cache on the dokuwiki side, you need to open and save the conf/local.php file (just add a space somewhere) or just by changing and saving a parameter in the configuration manager (described here : https://www.dokuwiki.org/caching)
- have you installed any plugin yet or is it only default plugins ?

**Comment by holisticagile** [comment]
Hey @nicolasprigent,

thank you for your fast response. I have a clean install. I tried so far cleaning my browser cache and also have a plugin for staling the cache on dokuwiki side. I was thinking, since the whole header was missing I messed something up in the configuration, yet there is not much to configure I guess.
I tried it out once again now and still... when I refresh the page on my other browser the whole header is gone and It shows only the start file.
I can imagine something in the site structure or so where a parser gets it wrong?

**Comment by nicolasprigent** [comment]
I tried on a fresh local install https://www.dokuwiki.org/install:dokuwiki_on_a_stick and the theme worked on first try. Could you try that?What language are you using for installation ?

**Comment by holisticagile** [comment]
I have this version: Release 2023-04-04a "Jack Jackrum"

I just did a new fresh install and did have the same issue, without doing anything, no plugin nothing. Is it possible that you need a specific php version? I also run nginx on my synology not apache

**Comment by nicolasprigent** [comment]
Can you access your logs here : 
**yourdomain**/doku.php?id=start&do=admin&page=logviewer
If there's php errors going on, they should be visible there.

**Comment by holisticagile** [comment]
ok, I did another fresh install without any configuration. The only thing i do is running it from port 8081, since my 80 is already used with my production dokuwiki.

yet, the bug exists. In the logging page there is no error shown. since i switched on debug mode there ist this comming:

![Bildschirmfoto 2023-07-20 um 12 02 34](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/77532551/4a2646d2-6995-4ec0-9355-daec29b6efcc)

Any other thoughts? I'm also open to do a live debug session if you are interested via zoom or so

**Comment by slackjeff** [comment]
same problem here

**Comment by nicolasprigent** [comment]
What I didn't understood on this issue, it's that you've installed your wiki as a public wiki. My wiki is a private one, so I didn't realised that public wikis should have a problem. Some lines of my code where hidding header and other things when user was not logged in. You can update the template as I've fixed the issue, let me know if it works for you now. Sorry for the inconvenience, it's still kind of a work in progress on my side ;)

**Comment by holisticagile** [comment]
@nicolasprigent, first of all, thank you for your support and commitment. 
I did give it a try and it works. That did the trick and I'm really happy. 
Thank you so much for helping! A lot of kudos to you!

**Comment by nicolasprigent** [comment]
Thanks a lot, glad it worked 👍 If you want to help me on this project, maybe you could help me add some new languages, like your native language, it should be great ! you can find the basic two translations here : https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/tree/main/lang
Have a great day

**Comment by holisticagile** [comment]
Yes, I'm open to put German there. Would be nice to integrate with the translate plugin. Can I just contribute on GutHub?

**Comment by nicolasprigent** [comment]
Sure you can, just make a new pull resquest with the german language 👍

**Comment by nicolasprigent** [comment]
You can directly add your translation in this branch : https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/tree/German-language
