### ISSUE TITLE
Long links overflow mobile view

### ISSUE THREAD

**Issue by Gabe-LSN** [nicolasprigent/Dokuwiki-Kiwiki-Theme#20]
There's just one thing that breaks the mobile layout when there are long links (such as a wayback link to a page).
This is mobile specific, for some reason links wrap correctly on desktop but not mobile browsers.

### Steps to reproduce
1. Use Kiwiki Theme
2. On a oage, insert a really long bare link that extends beyond a mobile view.
3. Load the page on a mobile browser and scroll side to side.

### Suggested fix
Change the wrapping on external links.
```css
.urlextern {
    word-break:break-all;
}
```

Great theme!

**Comment by nicolasprigent** [comment]
I've added the css rule, you can now update the theme. Thanks !
