### ISSUE TITLE
Darkmode color or text with Prosemirror for bulletpoint lists

### ISSUE THREAD

**Issue by poVoq** [nicolasprigent/Dokuwiki-Kiwiki-Theme#22]
With Prosemirror bullet point lists are black on a dark background in dark-mode, making them very hard to read. I hope that can be fixed in this very nice theme. See:

![grafik](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/940360/9969ed8b-88cf-4b1a-8a2a-960ed23c2076)

**Comment by nicolasprigent** [comment]
Hello, I'm not familiar with prosemirror, is it a dokuwiki plugin ?

**Comment by nicolasprigent** [comment]
Ok, I'll make specific CSS for this plugin. Is it only affecting bullet points or is there other things that doesn't work?
