### ISSUE TITLE
Edit pen only visible when logged in as admin

### ISSUE THREAD

**Issue by poVoq** [nicolasprigent/Dokuwiki-Kiwiki-Theme#23]
The little edit pen in the top right corner of a page to enter the edit mode seems to be only visible when you are logged in as an Dokuwiki admin.

When I set ACL to allow editing certain pages by other groups, this works fine on the default theme and I can edit pages as expected by adding `?do=edit` to the URL of that page, but the little edit button stays hidden for these non-admin users.

Thanks for looking into this.

**Comment by nicolasprigent** [comment]
Yes I've put the condition to be only on admin. I'll make an update to have the condition relying on ACL authorisation.

**Comment by poVoq** [comment]
I am getting users via AuthPDO from an external database and the ACL includes an wildcard placeholder like this:

![grafik](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/940360/80f04bed-a74d-4bc4-8a77-576c7ddc5e78)

I got the idea how to do it from here and it works with the default theme: https://forum.dokuwiki.org/d/22109-automatic-namespaces-and-acl-for-authpdo-derived-groups

**Comment by nicolasprigent** [comment]
That sounds really specific. Does this link still works ?
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/66468412/0eb0bf88-9f53-4b3b-bfa7-8f9a97b9c024)

**Comment by poVoq** [comment]
Yes that link seems to work as expected.

**Comment by poVoq** [comment]
I assume if I change [this line](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/blob/a82b09e77b5306e1a9527559110331758e15960d/classes/kiwiki_functions.php#L9) to:

`if ((auth_quickaclcheck($USERINFO['id']) >= AUTH_READ) && $action == 'show'){`

or so, it will always show the pen icon?

**Comment by nicolasprigent** [comment]
Sorry for late reply, I'll try to find some fix, that's a tricky one because I don't have the same environnement than yours to test. As soon as I get some free time.

**Comment by nicolasprigent** [comment]
Since the edit page button was working as you wanted, I've made a refactor of my edit button code, so now it uses the same dokuwiki classes that is used for the classic menu items. Let me know if that gives you the desired result on your install.

**Comment by poVoq** [comment]
Thanks!

It appears to be always visible now, which is fine with me.

**Comment by nicolasprigent** [comment]
Great !
