### ISSUE TITLE
使用模板出现问题

### ISSUE THREAD

**Issue by ZhongXiYi** [nicolasprigent/Dokuwiki-Kiwiki-Theme#24]
我是支持您的用户，在尝试使用这个模板的时候，出现了报错。希望得到您的帮助！
![问题](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/169547115/c7d8f0e7-d3d6-4503-bf68-829d5f9e069b)

**Comment by nicolasprigent** [comment]
Those are php warnings, it doesn't block the usage but it's anoying. Same than here : https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/issues/16
I'll make the necessary fix as soon as I get some free time.

**Comment by ZhongXiYi** [comment]
非常的感谢您，您的模板非常棒，我非常的喜欢，期待您的修复！再次感谢您！

**Comment by nicolasprigent** [comment]
You can update your theme, it should work without those warnings showing. Thanks for your interest on my theme.
