### ISSUE TITLE
Export to PDF on every page with DW2PDF plugin

### ISSUE THREAD

**Issue by poVoq** [nicolasprigent/Dokuwiki-Kiwiki-Theme#25]
Since upgrading to the latest version, an export to PDF link started showing up on every page and not only the page menu.

See:

![grafik](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/940360/e145a0e4-f980-4f30-9f1b-a49e6ddc2770)

This is with the following extension: https://www.dokuwiki.org/plugin:dw2pdf

**Comment by nicolasprigent** [comment]
Sorry for this bug, it's fixed caused by an unnecessary line of code. you can reinstall to get the fix

**Comment by poVoq** [comment]
Great, thanks for the quick fix!
