### ISSUE TITLE
Other plugin's icon turned into gray scale

### ISSUE THREAD

**Issue by Xiaoran134** [nicolasprigent/Dokuwiki-Kiwiki-Theme#27]
Hi，
Thanks for your wonderful template, I like it very much!
I've installed an plugin allows user to write colored  text : https://www.dokuwiki.org/plugin:color  
After the installation ，the colored text appears correctly, but the icons of this plugin turned into grayscale：
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/174193751/a4672bb3-0177-4e28-8a77-d6e9d0ec990f)

this problem doesn't show up in the default template "dokuwiki":
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/174193751/da52bd54-ecc8-4806-b41c-925827ab5c5e)

Dokuwiki version : https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz

Wondering if there's any solution ,many thanks！

**Comment by nicolasprigent** [comment]
yes I see, I wanted to have a consistency in the icon colors. I'll do the corrections affect only the first row of icons, not the popup ones.

**Comment by nicolasprigent** [comment]
it's fixed, let me know if it's ok on your side

**Comment by Xiaoran134** [comment]
@nicolasprigent it works perfect!  Thx👍

**Comment by Xiaoran134** [comment]
@nicolasprigent it works perfect! Thx👍
