### ISSUE TITLE
Full-Screen reset by site swtich

### ISSUE THREAD

**Issue by suther** [nicolasprigent/Dokuwiki-Kiwiki-Theme#28]
I am a fan of wide pages.
I like the full-screen-view you've build in. 

But I would love to have this full-screen mode all the time. 
If I start full-screen and click on a link (to navigate to another page in the wiki) the fullscreen is closed.

Would be nice if there could be a checkbox like "keep fullscreen" and as long as it's ticked, it won't switch back to normal view.

BTW: Isn't there any way to change the "default-layout" to be wider?
Would love to have an config-setting to remove this max-width value: 

![image](https://github.com/user-attachments/assets/6a52d6ab-7887-436c-a5d8-b80e6e51f80e)

**Comment by nicolasprigent** [comment]
hi @suther , the full screen button shouldn't be a permanent switch on the ui in my opinion, it's supposed to be a tool to read the content in a more focused way. But I think you'll be fine with the update that I've made. You can now choose a "Content Max Width" in the theme options. By default, it's the same width than before (1300px), but you can put whatever css value that you want now. Like 100% if you want.
![image](https://github.com/user-attachments/assets/ea844b3c-0a9f-438a-bb98-01ecc877606a)
Let me know if it's ok for you ?

**Comment by suther** [comment]
That's great, thank you. 
BTW: Is there a way to pre-set the light / dark mode in the settings? Would be awesome to force one of both as initial value.

**Comment by suther** [comment]
@nicolasprigent found that you missed to set this variable for the search-result: 

![image](https://github.com/user-attachments/assets/252c42a5-d79e-4171-880d-e9c5e1cbb38e)
