### ISSUE TITLE
Error in logs for "btn_bottom"

### ISSUE THREAD

**Issue by suther** [nicolasprigent/Dokuwiki-Kiwiki-Theme#30]
In the logs I got this error from kiwiki-theme: 

```
2024-10-01 08:17:58
E_WARNING: Undefined array key "btn_bottom"
/home/myPage/domains/wiki.myPage.com/public_html/inc/Menu/Item/AbstractItem.php(86)
#0 /home/myPage/domains/wiki.myPage.com/public_html/inc/Menu/Item/AbstractItem.php(86): dokuwiki\ErrorHandler::errorHandler()
#1 /home/myPage/domains/wiki.myPage.com/public_html/inc/Menu/Item/AbstractItem.php(104): dokuwiki\Menu\Item\AbstractItem->getLabel()
#2 /home/myPage/domains/wiki.myPage.com/public_html/lib/tpl/kiwiki/main.php(70): dokuwiki\Menu\Item\AbstractItem->getTitle()
#3 /home/myPage/domains/wiki.myPage.com/public_html/inc/actions.php(30): include('...')
#4 /home/myPage/domains/wiki.myPage.com/public_html/doku.php(131): act_dispatch()
```
A fulltext search in my Wiki-Folder Structure shows that this btn_button just appear in `/lib/tpl/kiwiki/classes/kiwiki_functions.php`

**Comment by nicolasprigent** [comment]
I've commented this lines of code since it wasn't used. Let me know if it still works on your installation or if you have new issues after this update.

**Comment by suther** [comment]
It is used... if you have activate the "to top & to bottom" button. 
You need to add it to your "plugin-lang" file and maybe rename the name of the variable. 
I've fixed this temporary by adding the btn_buttom as parameter to the default dokuwiki lang-file.

**Comment by nicolasprigent** [comment]
Ok, I've made a new update, and reactivated the code that I had commented. On my install, both buttons where working correctly but maybe I was missing something.
