### ISSUE TITLE
kiwiki template not properly aligned the Discussion plugin

### ISSUE THREAD

**Issue by Chris75forumname** [nicolasprigent/Dokuwiki-Kiwiki-Theme#33]
Hi, following issue was mentioned in the forum regarding your great template:
kiwiki template not properly aligned the Discussion plugin
https://forum.dokuwiki.org/d/22697-back-to-top-floating-button-at-mobile-view/5
Maybe you want to address this? I keep recommending your template because I like it alot! Cheers!

**Comment by nicolasprigent** [comment]
Hi @Chris75forumname,
I've made a fix on css to adress this issue about Discussion plugin
![discussion](https://github.com/user-attachments/assets/e40a21fd-8d10-49fd-93ec-576c436aa293)
Alignment was off, now it's better. Thanks for the input about this issue.

**Comment by Chris75forumname** [comment]
Great! Thanks for the quick reaction! Yours, Chris
