### ISSUE TITLE
Last update makes strange looking edit-buttons

### ISSUE THREAD

**Issue by christianprim** [nicolasprigent/Dokuwiki-Kiwiki-Theme#34]
I love the fix for the discussion plugin. Until now I had a quick and dirty fix in my usterstyle.css.

But with the new css the edit-buttons look strange to me. Is that intended?

What I see is
![Screenshot 2024-11-28 17 56 52](https://github.com/user-attachments/assets/c438a2e6-0ea6-470e-86f8-d13c0818a0cc)

**Comment by nicolasprigent** [comment]
Hi @christianprim it's not intentional. I just didn't see that when I was testing my CSS fix yesterday. I'll make an update asap, sorry for that

**Comment by christianprim** [comment]
No problem! Your theme and your support are so good. Many thanks for sharing.

**Comment by nicolasprigent** [comment]
It's fixed !

**Comment by christianprim** [comment]
Many thanks! (It's still not published, so I can't test it.)

**Comment by christianprim** [comment]
Thanks manually looking for the theme, I could force dokuwiki to update kiwiki. IT WORKS! Many thanks!
