### ISSUE TITLE
Filter in extension manager plugin doesn't work when screen is narrow

### ISSUE THREAD

**Issue by christianprim** [nicolasprigent/Dokuwiki-Kiwiki-Theme#6]
I think, there is a bug in the template using the extension manager in small screen size. All extensions are shown regardless of the filter (checkboxes). See screenshots:

Wide screen:
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/5284928/5249a93e-a40b-41c0-b848-692926a77420)

Small screen:
![image](https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/assets/5284928/0efbee85-202f-4536-9e60-49411aa7ecdc)

This doesn't happen with the standard template.

**Comment by nicolasprigent** [comment]
Hello, I've just updated the theme to fix the css issue that was the cause of the problem. Let me know if it worked for you

**Comment by christianprim** [comment]
Thanks! It works. Very good theme and fast response time to issues.
