### ISSUE TITLE
Working together with translation plugin

### ISSUE THREAD

**Issue by StephanSchrade** [nicolasprigent/Dokuwiki-Kiwiki-Theme#7]
Many thanks for your good plugin!
Is there any change to get it working together with the Translation Plugin?
Right now the language selector is not shown and the mainmenue can not be displayed in different languages.

**Comment by nicolasprigent** [comment]
hello @StephanSchrade I will investigate to find if I can make the theme compatible with this plugin.

**Comment by nicolasprigent** [comment]
I've just updated the theme, it's now compatible with translation plugin ;)
Let me know if it's working on your installation

**Comment by StephanSchrade** [comment]
Hello @nicolasprigent 
many thanks for the very very quick fix for the language selector!
Works like a charm.
Is there a way to make the mailmen translatable?

**Comment by nicolasprigent** [comment]
Thanks 👍
What do you refer to when you say make the mailmen translatable ?

**Comment by nicolasprigent** [comment]
If this is the left menu, all you have to do is to specify a page name in configuration, and then you'll have to edit one page menu for each language, for example if your menu name is mainmenu then you'll have en:mainmenu and fr: mainmenu. This will be separate menus pages and won't be dynamicly populated : each time you add something in a language you'll have to do it also for the other.

**Comment by nicolasprigent** [comment]
To edit the menus on each language, switch to desired language then click on the pen icon on top right of the left menu : it will go to the menu edition for the current language.

**Comment by StephanSchrade** [comment]
Thanks very much. Now I got it.
I did stumble upon the fact, that there is always "Menu" written on top of the mainmenu. And I cant't change that.

**Comment by nicolasprigent** [comment]
You should update the theme once more I've made a fix because menu wasn't showing up when current page was at higher level than 2. To get the correct translation of menu word please check the translate UI in translation plugin configuration. Currently there's only 3 language available in the theme so if you need something else don't hesitate to participate 😉

**Comment by StephanSchrade** [comment]
The new version is visible in the list of my plugins and there is an upgrade button, but I can't upgrade.
I'm still at 2023-09-30

**Comment by nicolasprigent** [comment]
I always forget to edit template info. It's ok now it should update. Sorry for that

**Comment by StephanSchrade** [comment]
Many thanks, now this works!
I have used the option to set a namespace starting point for the language namespaces but then the menu does not work.
I did reorganize my pages to have the en and de namespaces at root and then the mainmenu in different languages works.

One more thing, I have seen in your code that there will be a switch to hide the settings option in the main menu, but I think it is not finished. When do you plan to release that?

**Comment by nicolasprigent** [comment]
I'm not sure of what code you refer to. You want to hide the pencil icon ?

**Comment by nicolasprigent** [comment]
@StephanSchrade I close the issue, if you need more help on the last question let me know on a new issue.
